---
params:

platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: 5.5-jre8

inputs:
  - name: kafka-connect-bigquery

outputs:
  - name: workspace
  - name: kafka-connect-bigquery-version

run:
  path: kafka-connect-bigquery/ci/build.sh
